version: '3.4'

services:
  html:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
      - ./html:/html
    command: asciidoctor -n /workdir/data-management-handbook.adoc -D /html


  # Metanorma can maybe be used to generate content from yaml data but it doesn't work for pdf (yet)
  # See https://www.metanorma.com/author/topics/install/ and https://www.metanorma.com/author/topics/automation/yaml_to_text/
  pdf:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
      - ./pdf:/pdf
    command: asciidoctor-pdf -a pdf-themesdir=/workdir -a pdf-theme=dmh -n /workdir/data-management-handbook.adoc -D /pdf



