version: '3.4'

services:
  html:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
      - ./html:/html
    command: asciidoctor -n /workdir/data-management-handbook.adoc -D /html

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.asciidoctor
    volumes:
      - ./doc:/workdir
      - ./pdf:/pdf
    command: asciidoctor-pdf -a pdf-themesdir=/workdir -a pdf-theme=dmh -n /workdir/data-management-handbook.adoc -D /pdf



